import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          HomeScreenNotRegistered(),
        ]),
      ),
    );
  }
}

class HomeScreenNotRegistered extends StatelessWidget {
  const HomeScreenNotRegistered({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 640,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 245,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF44545),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(70),
                        bottomRight: Radius.circular(70),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 36,
                child: Container(
                  width: 25,
                  height: 14,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 99,
                top: 83,
                child: Text(
                  'Hello Zoharin',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 137,
                child: Container(
                  width: 148,
                  height: 236,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(40),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x33000000),
                        blurRadius: 10,
                        offset: Offset(2, 15),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 191,
                top: 137,
                child: Container(
                  width: 148,
                  height: 236,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(40),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x33000000),
                        blurRadius: 10,
                        offset: Offset(2, 15),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 156,
                child: SizedBox(
                  width: 135,
                  child: Text(
                    'Your Blood Group',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF502727),
                      fontSize: 18,
                      fontFamily: 'Montserrat',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 198,
                top: 161,
                child: SizedBox(
                  width: 135,
                  child: Text(
                    'Donor Status',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF502727),
                      fontSize: 18,
                      fontFamily: 'Montserrat',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 64,
                top: 259,
                child: Text(
                  'A+',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 50,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ),
              Positioned(
                left: 219,
                top: 214,
                child: Container(
                  width: 93,
                  height: 93,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFFC452),
                    shape: OvalBorder(side: BorderSide(width: 1)),
                  ),
                ),
              ),
              Positioned(
                left: 246,
                top: 284,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.80),
                  width: 62.94,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 7,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 291.77,
                top: 277.96,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-2.41),
                  width: 62.94,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 7,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 49,
                top: 451,
                child: Container(
                  width: 265,
                  height: 53,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFC40000),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(18),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 49,
                top: 451,
                child: Container(
                  width: 265,
                  height: 53,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFF0D0D),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(18),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 106,
                top: 466,
                child: Text(
                  'Request Donors',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 18,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 277,
                top: 469,
                child: Container(
                  width: 42,
                  height: 42,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFD6D6D6),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 277,
                top: 441,
                child: Container(
                  width: 42,
                  height: 42,
                  decoration: ShapeDecoration(
                    color: const Color(0xD6FF9595),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 516,
                child: Container(
                  width: 265,
                  height: 53,
                  decoration: ShapeDecoration(
                    color: Colors.white.withValues(alpha: 0.53),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(18),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 516,
                child: Container(
                  width: 265,
                  height: 53,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFF0000),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(18),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 116,
                top: 534,
                child: Text(
                  'Donate Blood',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 18,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 276,
                top: 534,
                child: Container(
                  width: 42,
                  height: 42,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF36868),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 276,
                top: 506,
                child: Container(
                  width: 42,
                  height: 42,
                  decoration: ShapeDecoration(
                    color: const Color(0xD6FF9595),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 204,
                top: 320,
                child: SizedBox(
                  width: 123,
                  child: Text(
                    'Please get checked up first to donate',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF9F8F8F),
                      fontSize: 13,
                      fontFamily: 'Montserrat',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 64,
                top: 583,
                child: SizedBox(
                  width: 238,
                  height: 15,
                  child: Text(
                    'Register for checkup',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 18,
                      fontFamily: 'Montserrat',
                      fontWeight: FontWeight.w700,
                      decoration: TextDecoration.underline,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}